
test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # NB: the tests to run are automatically deduced by the CI script according to the
    # content of the app's manifest. The declarations below allow to customize which
    # tests are ran, possibly add special test suite to test special args, or
    # declare which commits to test upgrade from.
    #
    # You can also decide (though this is discouraged!) to ban/ignore some tests,

    # exclude = ["install.private", "install.multi"]


    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    # By default, the CI will automagically fill the 'standard' args
    # such as domain, path, admin, is_public and password with relevant values
    # and also install args with a "default" provided in the manifest..
    # It should only make sense to declare custom args here for args with no default values

    # args.language = "fr_FR"
    # args.multisite = 0

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d8c645bb.name = "Initial commit / packaging v1"


[whatever]

    # On additional tests suites, you can decide to run only specific tests

    only = ["install.subdir"]
